# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pull Requests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Dotnet Publish
        run: dotnet publish -c Release --self-contained -r win-x64 -o ./artifact
  
      - name: archive release
        run: zip -r release.zip ./artifact
  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: publish
          path: ./release.zip
